Item list
brunors1/bitshouse pull request #4
Opened 2023-05-03 21:23 UTC by brunors1

Criação dos componentes ItemList e Item.

2023-05-04 17:10 UTC, angelarf requested changes

2023-05-04 17:10 UTC, angelarf commented on src/components/Item.js
> +                <div className="card h-100" key={id}>
A propriedade `key` precisa estar no primeiro nó, caso contrário não funcionará como esperado

Caso deseje ler sobre: https://react.dev/learn/rendering-lists#keeping-list-items-in-order-with-key

```
 <div className="col" key={id}>
   <div className="card h-100">
 ```

2023-05-04 17:10 UTC, angelarf commented on src/components/Item.js
> +                        <button type="button" className="btn btn-success">{description}</button>
💡 Dica (não obrigatório): Talvez a propriedade `description` deveria se chamar `buttonLabel`, para fazer um pouco mais de sentido quando lemos o código

2023-05-04 17:10 UTC, angelarf commented on src/components/ItemList.js
> +    const mockData = [
Como isso é uma constante, ele pode ser declarado fora da função. 
Internamente o react iria recriar essa constante toda vez que passasse por esse useEffect. 

Sugestão: mover para a linha 3 (antes da função)

2023-05-04 18:43 UTC, brunors1 commented on src/components/ItemList.js
> +    const mockData = [
Boa tarde!! 
Subi as alterações conforme orientado, pode verificar por favor se está tudo certo agora? Obrigado!!!!

2023-05-08 11:46 UTC, angelarf approved these changes
Parabéns pela entrega! 

Aprovado :D

2023-05-08 18:43 UTC, merged