CartContext adicionado ao projeto
brunors1/bitshouse pull request #8
Opened 2023-05-15 14:07 UTC by brunors1

Bom dia, Eu fiquei um pouco em dúvida se precisava ou não criar a página do cart já, mas acabei criando só o que foi pedido na entrega, se tiver que criar também a pagina e estrutura para essa mesma entrega me avisar por favor. Obrigado pela  ajuda de sempre !!

2023-05-16 23:23 UTC, angelarf requested changes
Oi Bruno!
Parabéns pela entrega!!

Acho que você fez o que o exercício pedia e está completinho!
Deixei alguns comentários, se precisar de ajuda para entender e/ou corrigir me dá um toque!

2023-05-16 23:23 UTC, angelarf commented on src/components/CartContext.js
Por uma questão de organização, sugiro salvar esse arquivo em uma pasta de `contexts` e não na de `components`

2023-05-16 23:23 UTC, angelarf commented on src/components/ItemDetail.js
> +    const existingItem = cartItems.find((cartItem) => cartItem.id === item.id);
Acredito que essa lógica não é necessária. Você faz a verificação de se o item já existe para atualizar dentro do context.

Outra observação, a assinatura da função `addItem` espera um item e uma quantidade. Nessa parte você utilizou passando o array de itens.

Sugestão: apagar esse `if/else` e adicionar apenas assim:

```
addItem(item, count)
```

2023-05-16 23:23 UTC, angelarf commented on src/components/ItemDetail.js
> +      id,
Percebi na execução que o id está vindo `undefined`, olhei o código e no `<ItemDetailContainer />` está faltando passar a prop `id` 😉 .
Para que o carrinho funcione direitinho, será necessário corrigir isso!

2023-05-18 14:47 UTC, brunors1 commented on src/components/ItemDetail.js
> +      id,
Acho que agora está certo

2023-05-18 14:48 UTC, brunors1 commented on src/components/ItemDetail.js
> +    const existingItem = cartItems.find((cartItem) => cartItem.id === item.id);
Esse aqui eu não tenho certeza se entendi muito bem, fiz algumas alterações e estou subindo outro commit, pode corrigir pra ver se eu fiz certo por favor? Obrigado!

2023-05-24 00:12 UTC, angelarf commented on src/components/ItemDetail.js
> +    const existingItem = cartItems.find((cartItem) => cartItem.id === item.id);
Isso mesmo! 
Ficou show!

2023-05-24 00:12 UTC, angelarf approved these changes
Aprovado, parabéns pela entrega

2023-05-25 19:29 UTC, merged